name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  cargo-fmt:
    name: cargo-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check formatting with cargo fmt
      run: cargo fmt --all -- --check

  build-ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
    - uses: actions/checkout@v1
    - name: Get latest version of stable Rust
      run: cargo build --release