name: release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-fmt:
    name: cargo-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check formatting with cargo fmt
        run: cargo fmt --all -- --check

  build-ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - name: Build for ubuntu
        uses: actions/checkout@v1
        run: cargo build --release
      - name: Upload bin
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-latest-bin
          path: target/release/arag 

  release-ubuntu:
    name: release-ubuntu
    runs-on: ubuntu-latest
    needs: build-ubuntu
    steps:
      - name: Download ubuntu bin
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest-bin
      - name: Create ubuntu release
        uses: actions/create-release@v1
        id: create-ubuntu-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.${{ github.run_number }}.0
          release_name: Release v0.${{ github.run_number }}.0
      - name: Upload ubuntu release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-ubuntu-release.outputs.upload_url }}
          asset_path: ./arag
          asset_name: arag-0.${{ github.run_number }}.0

